<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
	</array>
	<key>name</key>
	<string>HOCON</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#value</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>hash-comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.hocon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#.*$\n?)</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\+=</string>
					<key>name</key>
					<string>keyword.operator.hocon</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.boolean.hocon</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:^|\s)(true|false|yes|no|on|off|null)(?=$|\s)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:^|\s)(include (?:url|file|classpath))\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.include.hocon</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.include.hocon</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:^|\s)(include)\s</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list.hocon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.structure.array.hocon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.hocon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([^\s\]])</string>
					<key>name</key>
					<string>invalid.illegal.expected-list-separator.hocon</string>
				</dict>
			</array>
		</dict>
		<key>multiline-string</key>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.hocon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple.hocon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))</string>
					<key>name</key>
					<string>constant.character.escape.hocon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.hocon</string>
				</dict>
			</array>
		</dict>
		<key>name</key>
		<dict>
			<key>match</key>
			<string>([a-zA-Z_][a-zA-Z0-9_$\.-]*)</string>
			<key>name</key>
			<string>entity.name.function.hocon</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?)</string>
			<key>name</key>
			<string>constant.numeric.hocon</string>
		</dict>
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.hocon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#name</string>
					<key>name</key>
					<string>entity.name.function.hocon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?:=|:)|\s*(?=\{))</string>
					<key>name</key>
					<string>punctuation.separator.key-value.hocon</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>slashes-comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.hocon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//.*$\n?)</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.hocon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.hocon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))</string>
					<key>name</key>
					<string>constant.character.escape.hocon</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unrecognized-string-escape.hocon</string>
				</dict>
			</array>
		</dict>
		<key>substitution</key>
		<dict>
			<key>begin</key>
			<string>(\$\{\??)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.substitution.hocon</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>name</key>
			<string>variable.parameter.substitution.hocon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([a-zA-Z_][a-zA-Z0-9_$\.-]*)</string>
					<key>name</key>
					<string>variable.parameter.substitution.hocon</string>
				</dict>
			</array>
		</dict>
		<key>time-unit</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.hocon</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.time.unit.hocon</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\d+)\s*(nanoseconds?|microseconds?|milliseconds?|seconds?|minutes?|hours?|days?|ns|us|ms|s|m|h|d)</string>
		</dict>
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#hash-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#slashes-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#time-unit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#substitution</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#multiline-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.hocon</string>
	<key>uuid</key>
	<string>15e12a0a-a88e-47bd-a967-a8393605cd60</string>
</dict>
</plist>
